[workspace]
resolver = "3"
members = ["crates/haifisch-core", "haifisch-engine"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/languint/haifisch"
readme = "README.md"

[workspace.dependencies]

[workspace.lints.clippy]
pedantic = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }
unwrap_used = "deny"
expect_used = "deny"
unimplemented = "deny"
todo = "deny"
panic_in_result_fn = "deny"
panic = "deny"
exit = "deny"
